# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\Desktop\comTool\SerialTool\AdvancedSetting.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AdvancedForm(object):
    def setupUi(self, AdvancedForm):
        AdvancedForm.setObjectName("AdvancedForm")
        AdvancedForm.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AdvancedForm.sizePolicy().hasHeightForWidth())
        AdvancedForm.setSizePolicy(sizePolicy)
        AdvancedForm.setAcceptDrops(False)
        AdvancedForm.setAutoFillBackground(False)
        AdvancedForm.setSizeGripEnabled(True)
        AdvancedForm.setModal(False)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(AdvancedForm)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(AdvancedForm)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBoxReceive = QtWidgets.QCheckBox(self.tab)
        self.checkBoxReceive.setChecked(True)
        self.checkBoxReceive.setObjectName("checkBoxReceive")
        self.horizontalLayout_2.addWidget(self.checkBoxReceive)
        self.checkBoxSend = QtWidgets.QCheckBox(self.tab)
        self.checkBoxSend.setObjectName("checkBoxSend")
        self.horizontalLayout_2.addWidget(self.checkBoxSend)
        self.checkBoxLog = QtWidgets.QCheckBox(self.tab)
        self.checkBoxLog.setObjectName("checkBoxLog")
        self.horizontalLayout_2.addWidget(self.checkBoxLog)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.spinBoxShowPeriod = QtWidgets.QSpinBox(self.tab_2)
        self.spinBoxShowPeriod.setMinimum(1)
        self.spinBoxShowPeriod.setMaximum(1000)
        self.spinBoxShowPeriod.setProperty("value", 100)
        self.spinBoxShowPeriod.setDisplayIntegerBase(10)
        self.spinBoxShowPeriod.setObjectName("spinBoxShowPeriod")
        self.gridLayout.addWidget(self.spinBoxShowPeriod, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.spinBoxRecDelay = QtWidgets.QSpinBox(self.tab_2)
        self.spinBoxRecDelay.setMinimum(1)
        self.spinBoxRecDelay.setMaximum(1000)
        self.spinBoxRecDelay.setObjectName("spinBoxRecDelay")
        self.gridLayout.addWidget(self.spinBoxRecDelay, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.spinBoxSendPeriod = QtWidgets.QSpinBox(self.tab_2)
        self.spinBoxSendPeriod.setMinimum(1)
        self.spinBoxSendPeriod.setMaximum(1000)
        self.spinBoxSendPeriod.setProperty("value", 8)
        self.spinBoxSendPeriod.setDisplayIntegerBase(10)
        self.spinBoxSendPeriod.setObjectName("spinBoxSendPeriod")
        self.gridLayout.addWidget(self.spinBoxSendPeriod, 2, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButtonDefault = QtWidgets.QPushButton(AdvancedForm)
        self.pushButtonDefault.setObjectName("pushButtonDefault")
        self.horizontalLayout.addWidget(self.pushButtonDefault)
        self.pushButtonOk = QtWidgets.QPushButton(AdvancedForm)
        self.pushButtonOk.setObjectName("pushButtonOk")
        self.horizontalLayout.addWidget(self.pushButtonOk)
        self.pushButtonCancel = QtWidgets.QPushButton(AdvancedForm)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(AdvancedForm)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(AdvancedForm)

    def retranslateUi(self, AdvancedForm):
        _translate = QtCore.QCoreApplication.translate
        AdvancedForm.setWindowTitle(_translate("AdvancedForm", "Dialog"))
        self.checkBoxReceive.setText(_translate("AdvancedForm", "显示接收"))
        self.checkBoxSend.setText(_translate("AdvancedForm", "显示发送"))
        self.checkBoxLog.setText(_translate("AdvancedForm", "显示日志"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("AdvancedForm", "显示"))
        self.label.setText(_translate("AdvancedForm", "数据显示"))
        self.label_3.setText(_translate("AdvancedForm", "毫秒"))
        self.label_2.setText(_translate("AdvancedForm", "接收延迟"))
        self.label_4.setText(_translate("AdvancedForm", "毫秒"))
        self.label_5.setText(_translate("AdvancedForm", "发送周期"))
        self.label_11.setText(_translate("AdvancedForm", "毫秒"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("AdvancedForm", "周期"))
        self.pushButtonDefault.setText(_translate("AdvancedForm", "默认"))
        self.pushButtonOk.setText(_translate("AdvancedForm", "确定"))
        self.pushButtonCancel.setText(_translate("AdvancedForm", "取消"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AdvancedForm = QtWidgets.QDialog()
    ui = Ui_AdvancedForm()
    ui.setupUi(AdvancedForm)
    AdvancedForm.show()
    sys.exit(app.exec_())

