# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\Desktop\comTool\SerialTool\SerialPort.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(873, 750)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        MainWindow.setFont(font)
        MainWindow.setTabletTracking(False)
        MainWindow.setAutoFillBackground(False)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBoxSerialPort = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxSerialPort.setObjectName("comboBoxSerialPort")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBoxSerialPort)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBoxBaudRate = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxBaudRate.setEnabled(True)
        self.comboBoxBaudRate.setObjectName("comboBoxBaudRate")
        self.comboBoxBaudRate.addItem("")
        self.comboBoxBaudRate.addItem("")
        self.comboBoxBaudRate.addItem("")
        self.comboBoxBaudRate.addItem("")
        self.comboBoxBaudRate.addItem("")
        self.comboBoxBaudRate.addItem("")
        self.comboBoxBaudRate.addItem("")
        self.comboBoxBaudRate.addItem("")
        self.comboBoxBaudRate.addItem("")
        self.comboBoxBaudRate.addItem("")
        self.comboBoxBaudRate.addItem("")
        self.comboBoxBaudRate.addItem("")
        self.comboBoxBaudRate.addItem("")
        self.comboBoxBaudRate.addItem("")
        self.comboBoxBaudRate.addItem("")
        self.comboBoxBaudRate.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBoxBaudRate)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.comboBoxDataBits = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxDataBits.setEnabled(True)
        self.comboBoxDataBits.setObjectName("comboBoxDataBits")
        self.comboBoxDataBits.addItem("")
        self.comboBoxDataBits.addItem("")
        self.comboBoxDataBits.addItem("")
        self.comboBoxDataBits.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBoxDataBits)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.comboBoxParityBits = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxParityBits.setEnabled(True)
        self.comboBoxParityBits.setObjectName("comboBoxParityBits")
        self.comboBoxParityBits.addItem("")
        self.comboBoxParityBits.addItem("")
        self.comboBoxParityBits.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBoxParityBits)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.comboBoxStopBits = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxStopBits.setEnabled(True)
        self.comboBoxStopBits.setAcceptDrops(False)
        self.comboBoxStopBits.setObjectName("comboBoxStopBits")
        self.comboBoxStopBits.addItem("")
        self.comboBoxStopBits.addItem("")
        self.comboBoxStopBits.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBoxStopBits)
        self.pushButtonOpenSerialPort = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonOpenSerialPort.setAutoFillBackground(False)
        self.pushButtonOpenSerialPort.setObjectName("pushButtonOpenSerialPort")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.pushButtonOpenSerialPort)
        self.label.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.comboBoxSerialPort.raise_()
        self.comboBoxBaudRate.raise_()
        self.comboBoxDataBits.raise_()
        self.comboBoxParityBits.raise_()
        self.comboBoxStopBits.raise_()
        self.pushButtonOpenSerialPort.raise_()
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(131, 0))
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setMaximumSize(QtCore.QSize(61, 16))
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_11)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setMaximumSize(QtCore.QSize(61, 16))
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_12)
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setObjectName("label_18")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setObjectName("label_20")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setObjectName("label_22")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label_22)
        self.pushButtonClearReceiveDisplay = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButtonClearReceiveDisplay.setObjectName("pushButtonClearReceiveDisplay")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.pushButtonClearReceiveDisplay)
        self.pushButtonSaveReceiveData = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButtonSaveReceiveData.setObjectName("pushButtonSaveReceiveData")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.SpanningRole, self.pushButtonSaveReceiveData)
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setObjectName("label_21")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_21)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout_6 = QtWidgets.QFormLayout(self.groupBox_4)
        self.formLayout_6.setObjectName("formLayout_6")
        self.checkBoxHex = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBoxHex.setObjectName("checkBoxHex")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.checkBoxHex)
        self.checkBoxRTS = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBoxRTS.setObjectName("checkBoxRTS")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.checkBoxRTS)
        self.checkBoxDTR = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBoxDTR.setObjectName("checkBoxDTR")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.checkBoxDTR)
        self.pushButtonSreialMode = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButtonSreialMode.setObjectName("pushButtonSreialMode")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.pushButtonSreialMode)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 712, 210))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textEditReceiveData = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditReceiveData.sizePolicy().hasHeightForWidth())
        self.textEditReceiveData.setSizePolicy(sizePolicy)
        self.textEditReceiveData.setReadOnly(True)
        self.textEditReceiveData.setObjectName("textEditReceiveData")
        self.verticalLayout_3.addWidget(self.textEditReceiveData)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.tabWidgetRobotMode = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidgetRobotMode.sizePolicy().hasHeightForWidth())
        self.tabWidgetRobotMode.setSizePolicy(sizePolicy)
        self.tabWidgetRobotMode.setObjectName("tabWidgetRobotMode")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.robotOpen = QtWidgets.QPushButton(self.tab_3)
        self.robotOpen.setMinimumSize(QtCore.QSize(0, 0))
        self.robotOpen.setObjectName("robotOpen")
        self.gridLayout.addWidget(self.robotOpen, 0, 1, 1, 1)
        self.robotClose = QtWidgets.QPushButton(self.tab_3)
        self.robotClose.setEnabled(False)
        self.robotClose.setObjectName("robotClose")
        self.gridLayout.addWidget(self.robotClose, 0, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_3)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.joint0MoveL = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.joint0MoveL.sizePolicy().hasHeightForWidth())
        self.joint0MoveL.setSizePolicy(sizePolicy)
        self.joint0MoveL.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.joint0MoveL.setAutoFillBackground(False)
        self.joint0MoveL.setStyleSheet("background-image: url(:/pic/icon/Left1.png);\n"
"")
        self.joint0MoveL.setText("")
        self.joint0MoveL.setObjectName("joint0MoveL")
        self.gridLayout.addWidget(self.joint0MoveL, 1, 1, 1, 1)
        self.joint0MoveR = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.joint0MoveR.sizePolicy().hasHeightForWidth())
        self.joint0MoveR.setSizePolicy(sizePolicy)
        self.joint0MoveR.setStyleSheet("background-image: url(:/pic/icon/Right1.png);")
        self.joint0MoveR.setText("")
        self.joint0MoveR.setObjectName("joint0MoveR")
        self.gridLayout.addWidget(self.joint0MoveR, 1, 2, 1, 1)
        self.joint0WorkMode = QtWidgets.QLabel(self.tab_3)
        self.joint0WorkMode.setObjectName("joint0WorkMode")
        self.gridLayout.addWidget(self.joint0WorkMode, 1, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 2, 0, 1, 1)
        self.joint1MoveL = QtWidgets.QPushButton(self.tab_3)
        self.joint1MoveL.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.joint1MoveL.setAutoFillBackground(False)
        self.joint1MoveL.setStyleSheet("background-image: url(:/pic/icon/Left1.png);\n"
"")
        self.joint1MoveL.setText("")
        self.joint1MoveL.setObjectName("joint1MoveL")
        self.gridLayout.addWidget(self.joint1MoveL, 2, 1, 1, 1)
        self.joint1MoveR = QtWidgets.QPushButton(self.tab_3)
        self.joint1MoveR.setStyleSheet("background-image: url(:/pic/icon/Right1.png);")
        self.joint1MoveR.setText("")
        self.joint1MoveR.setObjectName("joint1MoveR")
        self.gridLayout.addWidget(self.joint1MoveR, 2, 2, 1, 1)
        self.joint1WorkMode = QtWidgets.QLabel(self.tab_3)
        self.joint1WorkMode.setObjectName("joint1WorkMode")
        self.gridLayout.addWidget(self.joint1WorkMode, 2, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 3, 0, 1, 1)
        self.joint2MoveL = QtWidgets.QPushButton(self.tab_3)
        self.joint2MoveL.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.joint2MoveL.setAutoFillBackground(False)
        self.joint2MoveL.setStyleSheet("background-image: url(:/pic/icon/Left1.png);\n"
"")
        self.joint2MoveL.setText("")
        self.joint2MoveL.setObjectName("joint2MoveL")
        self.gridLayout.addWidget(self.joint2MoveL, 3, 1, 1, 1)
        self.joint2MoveR = QtWidgets.QPushButton(self.tab_3)
        self.joint2MoveR.setStyleSheet("background-image: url(:/pic/icon/Right1.png);")
        self.joint2MoveR.setText("")
        self.joint2MoveR.setObjectName("joint2MoveR")
        self.gridLayout.addWidget(self.joint2MoveR, 3, 2, 1, 1)
        self.joint2WorkMode = QtWidgets.QLabel(self.tab_3)
        self.joint2WorkMode.setObjectName("joint2WorkMode")
        self.gridLayout.addWidget(self.joint2WorkMode, 3, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 4, 0, 1, 1)
        self.joint3MoveL = QtWidgets.QPushButton(self.tab_3)
        self.joint3MoveL.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.joint3MoveL.setAutoFillBackground(False)
        self.joint3MoveL.setStyleSheet("background-image: url(:/pic/icon/Left1.png);\n"
"")
        self.joint3MoveL.setText("")
        self.joint3MoveL.setObjectName("joint3MoveL")
        self.gridLayout.addWidget(self.joint3MoveL, 4, 1, 1, 1)
        self.joint3MoveR = QtWidgets.QPushButton(self.tab_3)
        self.joint3MoveR.setStyleSheet("background-image: url(:/pic/icon/Right1.png);")
        self.joint3MoveR.setText("")
        self.joint3MoveR.setObjectName("joint3MoveR")
        self.gridLayout.addWidget(self.joint3MoveR, 4, 2, 1, 1)
        self.joint3WorkMode = QtWidgets.QLabel(self.tab_3)
        self.joint3WorkMode.setObjectName("joint3WorkMode")
        self.gridLayout.addWidget(self.joint3WorkMode, 4, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 5, 0, 1, 1)
        self.joint4MoveL = QtWidgets.QPushButton(self.tab_3)
        self.joint4MoveL.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.joint4MoveL.setAutoFillBackground(False)
        self.joint4MoveL.setStyleSheet("background-image: url(:/pic/icon/Left1.png);\n"
"")
        self.joint4MoveL.setText("")
        self.joint4MoveL.setObjectName("joint4MoveL")
        self.gridLayout.addWidget(self.joint4MoveL, 5, 1, 1, 1)
        self.joint4MoveR = QtWidgets.QPushButton(self.tab_3)
        self.joint4MoveR.setStyleSheet("background-image: url(:/pic/icon/Right1.png);")
        self.joint4MoveR.setText("")
        self.joint4MoveR.setObjectName("joint4MoveR")
        self.gridLayout.addWidget(self.joint4MoveR, 5, 2, 1, 1)
        self.joint4WorkMode = QtWidgets.QLabel(self.tab_3)
        self.joint4WorkMode.setObjectName("joint4WorkMode")
        self.gridLayout.addWidget(self.joint4WorkMode, 5, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 6, 0, 1, 1)
        self.joint5MoveL = QtWidgets.QPushButton(self.tab_3)
        self.joint5MoveL.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.joint5MoveL.setAutoFillBackground(False)
        self.joint5MoveL.setStyleSheet("background-image: url(:/pic/icon/Left1.png);\n"
"")
        self.joint5MoveL.setText("")
        self.joint5MoveL.setObjectName("joint5MoveL")
        self.gridLayout.addWidget(self.joint5MoveL, 6, 1, 1, 1)
        self.joint5MoveR = QtWidgets.QPushButton(self.tab_3)
        self.joint5MoveR.setStyleSheet("background-image: url(:/pic/icon/Right1.png);")
        self.joint5MoveR.setText("")
        self.joint5MoveR.setObjectName("joint5MoveR")
        self.gridLayout.addWidget(self.joint5MoveR, 6, 2, 1, 1)
        self.joint5WorkMode = QtWidgets.QLabel(self.tab_3)
        self.joint5WorkMode.setObjectName("joint5WorkMode")
        self.gridLayout.addWidget(self.joint5WorkMode, 6, 3, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 7, 0, 1, 1)
        self.joint6WorkMode = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.joint6WorkMode.sizePolicy().hasHeightForWidth())
        self.joint6WorkMode.setSizePolicy(sizePolicy)
        self.joint6WorkMode.setObjectName("joint6WorkMode")
        self.gridLayout.addWidget(self.joint6WorkMode, 7, 3, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(433, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.tabWidgetRobotMode.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.formLayout_5 = QtWidgets.QFormLayout(self.tab_4)
        self.formLayout_5.setObjectName("formLayout_5")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_23 = QtWidgets.QLabel(self.tab_4)
        self.label_23.setObjectName("label_23")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.singleJointParam = QtWidgets.QComboBox(self.tab_4)
        self.singleJointParam.setObjectName("singleJointParam")
        self.singleJointParam.addItem("")
        self.singleJointParam.addItem("")
        self.singleJointParam.addItem("")
        self.singleJointParam.addItem("")
        self.singleJointParam.addItem("")
        self.singleJointParam.addItem("")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.singleJointParam)
        self.label_24 = QtWidgets.QLabel(self.tab_4)
        self.label_24.setObjectName("label_24")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.singleJointSpeed = QtWidgets.QSpinBox(self.tab_4)
        self.singleJointSpeed.setMinimum(-3000)
        self.singleJointSpeed.setMaximum(3000)
        self.singleJointSpeed.setSingleStep(100)
        self.singleJointSpeed.setProperty("value", 0)
        self.singleJointSpeed.setDisplayIntegerBase(10)
        self.singleJointSpeed.setObjectName("singleJointSpeed")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.singleJointSpeed)
        self.startSingleRotate = QtWidgets.QPushButton(self.tab_4)
        self.startSingleRotate.setObjectName("startSingleRotate")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.startSingleRotate)
        self.stopSingleRotate = QtWidgets.QPushButton(self.tab_4)
        self.stopSingleRotate.setObjectName("stopSingleRotate")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.stopSingleRotate)
        self.formLayout_5.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.formLayout_4)
        self.tabWidgetRobotMode.addTab(self.tab_4, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidgetRobotMode.addTab(self.tab_6, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.textEditRobotLog = QtWidgets.QTextEdit(self.tab_5)
        self.textEditRobotLog.setGeometry(QtCore.QRect(10, 10, 691, 221))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textEditRobotLog.setFont(font)
        self.textEditRobotLog.setReadOnly(True)
        self.textEditRobotLog.setObjectName("textEditRobotLog")
        self.tabWidgetRobotMode.addTab(self.tab_5, "")
        self.verticalLayout.addWidget(self.tabWidgetRobotMode)
        self.tabWidgetNormalSerial = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidgetNormalSerial.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidgetNormalSerial.sizePolicy().hasHeightForWidth())
        self.tabWidgetNormalSerial.setSizePolicy(sizePolicy)
        self.tabWidgetNormalSerial.setMaximumSize(QtCore.QSize(16777215, 200))
        self.tabWidgetNormalSerial.setUsesScrollButtons(True)
        self.tabWidgetNormalSerial.setDocumentMode(True)
        self.tabWidgetNormalSerial.setObjectName("tabWidgetNormalSerial")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Tx_timer_1 = QtWidgets.QCheckBox(self.tab_2)
        self.Tx_timer_1.setObjectName("Tx_timer_1")
        self.horizontalLayout_2.addWidget(self.Tx_timer_1)
        self.Transmit_1 = QtWidgets.QPushButton(self.tab_2)
        self.Transmit_1.setStyleSheet("")
        self.Transmit_1.setObjectName("Transmit_1")
        self.horizontalLayout_2.addWidget(self.Transmit_1)
        self.textEdit_1 = QtWidgets.QTextEdit(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_1.sizePolicy().hasHeightForWidth())
        self.textEdit_1.setSizePolicy(sizePolicy)
        self.textEdit_1.setBaseSize(QtCore.QSize(123, 123))
        self.textEdit_1.setLineWidth(1)
        self.textEdit_1.setMidLineWidth(0)
        self.textEdit_1.setObjectName("textEdit_1")
        self.horizontalLayout_2.addWidget(self.textEdit_1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Tx_timer_2 = QtWidgets.QCheckBox(self.tab_2)
        self.Tx_timer_2.setChecked(False)
        self.Tx_timer_2.setObjectName("Tx_timer_2")
        self.horizontalLayout_3.addWidget(self.Tx_timer_2)
        self.Transmit_2 = QtWidgets.QPushButton(self.tab_2)
        self.Transmit_2.setObjectName("Transmit_2")
        self.horizontalLayout_3.addWidget(self.Transmit_2)
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_2.setEnabled(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.horizontalLayout_3.addWidget(self.textEdit_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Tx_timer_3 = QtWidgets.QCheckBox(self.tab_2)
        self.Tx_timer_3.setObjectName("Tx_timer_3")
        self.horizontalLayout_4.addWidget(self.Tx_timer_3)
        self.Transmit_3 = QtWidgets.QPushButton(self.tab_2)
        self.Transmit_3.setObjectName("Transmit_3")
        self.horizontalLayout_4.addWidget(self.Transmit_3)
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_3.setObjectName("textEdit_3")
        self.horizontalLayout_4.addWidget(self.textEdit_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Tx_timer_4 = QtWidgets.QCheckBox(self.tab_2)
        self.Tx_timer_4.setObjectName("Tx_timer_4")
        self.horizontalLayout_5.addWidget(self.Tx_timer_4)
        self.Transmit_4 = QtWidgets.QPushButton(self.tab_2)
        self.Transmit_4.setObjectName("Transmit_4")
        self.horizontalLayout_5.addWidget(self.Transmit_4)
        self.textEdit_4 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_4.setObjectName("textEdit_4")
        self.horizontalLayout_5.addWidget(self.textEdit_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.tabWidgetNormalSerial.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.comboBoxJointId = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBoxJointId.setObjectName("comboBoxJointId")
        self.comboBoxJointId.addItem("")
        self.comboBoxJointId.addItem("")
        self.comboBoxJointId.addItem("")
        self.comboBoxJointId.addItem("")
        self.comboBoxJointId.addItem("")
        self.comboBoxJointId.addItem("")
        self.comboBoxJointId.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBoxJointId)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.comboBoxParameter = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBoxParameter.setObjectName("comboBoxParameter")
        self.comboBoxParameter.addItem("")
        self.comboBoxParameter.addItem("")
        self.comboBoxParameter.addItem("")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBoxParameter)
        self.pushButtonLoadSerialData = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonLoadSerialData.setObjectName("pushButtonLoadSerialData")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.pushButtonLoadSerialData)
        self.pushButtonDataVisualized = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonDataVisualized.setCheckable(False)
        self.pushButtonDataVisualized.setObjectName("pushButtonDataVisualized")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.pushButtonDataVisualized)
        self.horizontalLayout_6.addWidget(self.groupBox_2)
        self.matplotlibWidgetJointParam = MatplotlibWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matplotlibWidgetJointParam.sizePolicy().hasHeightForWidth())
        self.matplotlibWidgetJointParam.setSizePolicy(sizePolicy)
        self.matplotlibWidgetJointParam.setMinimumSize(QtCore.QSize(560, 0))
        self.matplotlibWidgetJointParam.setObjectName("matplotlibWidgetJointParam")
        self.horizontalLayout_6.addWidget(self.matplotlibWidgetJointParam)
        self.tabWidgetNormalSerial.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidgetNormalSerial)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setAutoFillBackground(False)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 873, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menuBar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menuBar)
        self.actionFile = QtWidgets.QAction(MainWindow)
        self.actionFile.setObjectName("actionFile")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAdvanced = QtWidgets.QAction(MainWindow)
        self.actionAdvanced.setObjectName("actionAdvanced")
        self.actionOffline = QtWidgets.QAction(MainWindow)
        self.actionOffline.setObjectName("actionOffline")
        self.actionOnline = QtWidgets.QAction(MainWindow)
        self.actionOnline.setObjectName("actionOnline")
        self.menu_2.addAction(self.actionHelp)
        self.menu_3.addAction(self.actionFile)
        self.menu_3.addAction(self.actionOffline)
        self.menu_3.addAction(self.actionOnline)
        self.menu_4.addAction(self.actionAdvanced)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())
        self.menuBar.addAction(self.menu_4.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidgetRobotMode.setCurrentIndex(0)
        self.tabWidgetNormalSerial.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "琦星北京电机参数可视化工具"))
        self.groupBox.setTitle(_translate("MainWindow", "串口设置"))
        self.label.setText(_translate("MainWindow", "串口号"))
        self.label_3.setText(_translate("MainWindow", "波特率"))
        self.comboBoxBaudRate.setItemText(0, _translate("MainWindow", "921600"))
        self.comboBoxBaudRate.setItemText(1, _translate("MainWindow", "480800"))
        self.comboBoxBaudRate.setItemText(2, _translate("MainWindow", "230400"))
        self.comboBoxBaudRate.setItemText(3, _translate("MainWindow", "115200"))
        self.comboBoxBaudRate.setItemText(4, _translate("MainWindow", "57600"))
        self.comboBoxBaudRate.setItemText(5, _translate("MainWindow", "38400"))
        self.comboBoxBaudRate.setItemText(6, _translate("MainWindow", "28800"))
        self.comboBoxBaudRate.setItemText(7, _translate("MainWindow", "19200"))
        self.comboBoxBaudRate.setItemText(8, _translate("MainWindow", "14400"))
        self.comboBoxBaudRate.setItemText(9, _translate("MainWindow", "9600"))
        self.comboBoxBaudRate.setItemText(10, _translate("MainWindow", "4800"))
        self.comboBoxBaudRate.setItemText(11, _translate("MainWindow", "2400"))
        self.comboBoxBaudRate.setItemText(12, _translate("MainWindow", "1200"))
        self.comboBoxBaudRate.setItemText(13, _translate("MainWindow", "600"))
        self.comboBoxBaudRate.setItemText(14, _translate("MainWindow", "300"))
        self.comboBoxBaudRate.setItemText(15, _translate("MainWindow", "110"))
        self.label_4.setText(_translate("MainWindow", "数据位"))
        self.comboBoxDataBits.setItemText(0, _translate("MainWindow", "8"))
        self.comboBoxDataBits.setItemText(1, _translate("MainWindow", "7"))
        self.comboBoxDataBits.setItemText(2, _translate("MainWindow", "6"))
        self.comboBoxDataBits.setItemText(3, _translate("MainWindow", "5"))
        self.label_5.setText(_translate("MainWindow", "校验位"))
        self.comboBoxParityBits.setItemText(0, _translate("MainWindow", "0"))
        self.comboBoxParityBits.setItemText(1, _translate("MainWindow", "1"))
        self.comboBoxParityBits.setItemText(2, _translate("MainWindow", "2"))
        self.label_6.setText(_translate("MainWindow", "停止位"))
        self.comboBoxStopBits.setItemText(0, _translate("MainWindow", "1"))
        self.comboBoxStopBits.setItemText(1, _translate("MainWindow", "1.5"))
        self.comboBoxStopBits.setItemText(2, _translate("MainWindow", "2"))
        self.pushButtonOpenSerialPort.setText(_translate("MainWindow", "打开串口"))
        self.groupBox_3.setTitle(_translate("MainWindow", "数据区"))
        self.label_7.setText(_translate("MainWindow", "收帧数"))
        self.label_11.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "收字节"))
        self.label_12.setText(_translate("MainWindow", "0"))
        self.label_18.setText(_translate("MainWindow", "发帧数"))
        self.label_20.setText(_translate("MainWindow", "发字节"))
        self.label_22.setText(_translate("MainWindow", "0"))
        self.pushButtonClearReceiveDisplay.setText(_translate("MainWindow", "清空显示"))
        self.pushButtonSaveReceiveData.setText(_translate("MainWindow", "保存数据"))
        self.label_21.setText(_translate("MainWindow", "0"))
        self.groupBox_4.setTitle(_translate("MainWindow", "特殊设置"))
        self.checkBoxHex.setText(_translate("MainWindow", "十六进制"))
        self.checkBoxRTS.setText(_translate("MainWindow", "RTS"))
        self.checkBoxDTR.setText(_translate("MainWindow", "DTR"))
        self.pushButtonSreialMode.setText(_translate("MainWindow", "机械臂模式"))
        self.robotOpen.setText(_translate("MainWindow", "开"))
        self.robotClose.setText(_translate("MainWindow", "关"))
        self.label_19.setText(_translate("MainWindow", "工作状态"))
        self.label_2.setText(_translate("MainWindow", "基座"))
        self.joint0WorkMode.setText(_translate("MainWindow", "关闭电源"))
        self.label_13.setText(_translate("MainWindow", "肩部"))
        self.joint1WorkMode.setText(_translate("MainWindow", "关闭电源"))
        self.label_14.setText(_translate("MainWindow", "肘部"))
        self.joint2WorkMode.setText(_translate("MainWindow", "关闭电源"))
        self.label_15.setText(_translate("MainWindow", "手腕1"))
        self.joint3WorkMode.setText(_translate("MainWindow", "关闭电源"))
        self.label_16.setText(_translate("MainWindow", "手腕2"))
        self.joint4WorkMode.setText(_translate("MainWindow", "关闭电源"))
        self.label_17.setText(_translate("MainWindow", "手腕3"))
        self.joint5WorkMode.setText(_translate("MainWindow", "关闭电源"))
        self.label_26.setText(_translate("MainWindow", "工具"))
        self.joint6WorkMode.setText(_translate("MainWindow", "关闭电源"))
        self.tabWidgetRobotMode.setTabText(self.tabWidgetRobotMode.indexOf(self.tab_3), _translate("MainWindow", "初始化机器人"))
        self.label_23.setText(_translate("MainWindow", "关节："))
        self.singleJointParam.setItemText(0, _translate("MainWindow", "基座"))
        self.singleJointParam.setItemText(1, _translate("MainWindow", "肩部"))
        self.singleJointParam.setItemText(2, _translate("MainWindow", "肘部"))
        self.singleJointParam.setItemText(3, _translate("MainWindow", "手腕1"))
        self.singleJointParam.setItemText(4, _translate("MainWindow", "手腕2"))
        self.singleJointParam.setItemText(5, _translate("MainWindow", "手腕3"))
        self.label_24.setText(_translate("MainWindow", "速度："))
        self.startSingleRotate.setText(_translate("MainWindow", "开始"))
        self.stopSingleRotate.setText(_translate("MainWindow", "停止"))
        self.tabWidgetRobotMode.setTabText(self.tabWidgetRobotMode.indexOf(self.tab_4), _translate("MainWindow", "单轴旋转"))
        self.tabWidgetRobotMode.setTabText(self.tabWidgetRobotMode.indexOf(self.tab_6), _translate("MainWindow", "机械臂"))
        self.tabWidgetRobotMode.setTabText(self.tabWidgetRobotMode.indexOf(self.tab_5), _translate("MainWindow", "日志"))
        self.Tx_timer_1.setText(_translate("MainWindow", "定时"))
        self.Transmit_1.setText(_translate("MainWindow", "发送1"))
        self.textEdit_1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">12 02 82 02 82 02 82 02 82 02 82 02 82 03 95 40 71 01</p></body></html>"))
        self.Tx_timer_2.setText(_translate("MainWindow", "定时"))
        self.Transmit_2.setText(_translate("MainWindow", "发送2"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">12 02 84 02 84 02 84 02 84 02 84 02 84 03 95 40 D2 AE</p></body></html>"))
        self.Tx_timer_3.setText(_translate("MainWindow", "定时"))
        self.Transmit_3.setText(_translate("MainWindow", "发送3"))
        self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">30 07 0A 00 1F AE 00 00 07 0A 00 1F AE 00 00 07 0A 00 1F AE 00 00 07 0A 00 10 E5 00 00 07 0A 00 10 E5 00 00 07 0A 00 10 E5 00 00 03 95 40 3F 54</p></body></html>"))
        self.Tx_timer_4.setText(_translate("MainWindow", "定时"))
        self.Transmit_4.setText(_translate("MainWindow", "发送4"))
        self.tabWidgetNormalSerial.setTabText(self.tabWidgetNormalSerial.indexOf(self.tab_2), _translate("MainWindow", "发送数据"))
        self.groupBox_2.setTitle(_translate("MainWindow", "机械臂参数设置"))
        self.label_8.setText(_translate("MainWindow", "关节"))
        self.comboBoxJointId.setItemText(0, _translate("MainWindow", "基座"))
        self.comboBoxJointId.setItemText(1, _translate("MainWindow", "肩部"))
        self.comboBoxJointId.setItemText(2, _translate("MainWindow", "肘部"))
        self.comboBoxJointId.setItemText(3, _translate("MainWindow", "手腕1"))
        self.comboBoxJointId.setItemText(4, _translate("MainWindow", "手腕2"))
        self.comboBoxJointId.setItemText(5, _translate("MainWindow", "手腕3"))
        self.comboBoxJointId.setItemText(6, _translate("MainWindow", "工具板"))
        self.label_9.setText(_translate("MainWindow", "参数  "))
        self.comboBoxParameter.setItemText(0, _translate("MainWindow", "速度"))
        self.comboBoxParameter.setItemText(1, _translate("MainWindow", "位置"))
        self.comboBoxParameter.setItemText(2, _translate("MainWindow", "电流"))
        self.pushButtonLoadSerialData.setText(_translate("MainWindow", "打开数据"))
        self.pushButtonDataVisualized.setText(_translate("MainWindow", "显示图像"))
        self.tabWidgetNormalSerial.setTabText(self.tabWidgetNormalSerial.indexOf(self.tab), _translate("MainWindow", "分析数据"))
        self.menuFile.setTitle(_translate("MainWindow", "文件"))
        self.menu.setTitle(_translate("MainWindow", "编辑"))
        self.menu_2.setTitle(_translate("MainWindow", "帮助"))
        self.menu_3.setTitle(_translate("MainWindow", "工具"))
        self.menu_4.setTitle(_translate("MainWindow", "设置"))
        self.actionFile.setText(_translate("MainWindow", "计算CRC"))
        self.actionHelp.setText(_translate("MainWindow", "使用说明"))
        self.actionHelp.setToolTip(_translate("MainWindow", "使用说明"))
        self.actionAdvanced.setText(_translate("MainWindow", "高级"))
        self.actionAdvanced.setToolTip(_translate("MainWindow", "高级选项"))
        self.actionOffline.setText(_translate("MainWindow", "离线数据分析"))
        self.actionOnline.setText(_translate("MainWindow", "实时数据分析"))

from MatplotlibWidget import MatplotlibWidget
import apprcc_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

